### ISSUE TITLE
Multi-file preview [looking for testers!]

### ISSUE THREAD

**Issue by kuator** [smjonas/inc-rename.nvim#5]

**Comment by smjonas** [comment]
The highlighting does not work across multiple files at the moment, no. I tried implementing this feature, however there are some issues with restoring the state of the buffer. See this video:

https://user-images.githubusercontent.com/40792180/171994054-c6a92128-90a9-4810-b669-0b64d530b243.mp4

If someone knows how to implement this, let me know.

**Comment by smjonas** [comment]
### Announcement

I have now managed to implement this feature! It is currently in beta, that means you must opt-in to use it. You can enable it like this:
```lua
require("inc_rename.nvim").setup {
  multifile_preview = true,
}
```
Please test this feature and let me know what you think and whether there are any issues! I hope you guys enjoy this, I think it turned out really useful! Once a few users have tested it, I'll make this the default option. 

Here is a quick demo how it should look like:

https://user-images.githubusercontent.com/40792180/173162089-52a09a01-93f7-452d-b9d0-5868dfb95df0.mp4

**Comment by famiu** [comment]
> @famiu By any chance, do you know if there is a way to handle command-previews across multiple buffers? I started implementing this [here](https://github.com/smjonas/inc-rename.nvim/blob/multifile_experiments/lua/inc_rename/init.lua) but as I said restoring the previous state of the buffers becomes difficult.

I'll discuss with the Neovim devs regarding whether we can implement multi-buffer preview support into core. It should be fairly trivial to implement.
