### ISSUE TITLE
[Bug] Index out of bounds

### ISSUE THREAD

**Issue by akinsho** [smjonas/inc-rename.nvim#7]
Hi 👋🏿

This plugin is a fantastic idea @smjonas thanks for creating it

I've just started using it this morning and am occasionally hitting the following error whilst just testing this out

```
Error executing vim.schedule lua callback: ...ack/packer/start/inc-rename.nvim/lua/inc_rename/init.lua:38: Index out of bounds                                                       
stack traceback:                                                                                                                                                                     
        [C]: in function 'nvim_buf_get_lines'                                                                                                                                        
        ...ack/packer/start/inc-rename.nvim/lua/inc_rename/init.lua:38: in function 'handler'                                                                                        
        ...r/neovim/HEAD-9961a97/share/nvim/runtime/lua/vim/lsp.lua:1173: in function ''                                                                                             
        vim/_editor.lua: in function <vim/_editor.lua:0>  
```

Seems that on the following line
https://github.com/smjonas/inc-rename.nvim/blob/800382c2451e79ba9482d6b40d9395c85e45325f/lua/inc_rename/init.lua#L38
There should maybe be a check to make sure the line is not out of bounds before doing an access of the table. No idea why the line is out of bounds though

**Comment by smjonas** [comment]
Thanks for checking out my plugin! Could you check if you can still reproduce this issue on the latest version? I accidentally used the number `0` instead of a boolean for the `strict_indexing` argument passed to `vim.api.nvim_buf_get_lines`. With `strict_indexing` now set to `false`, maybe this issue is now resolved?

**Comment by akinsho** [comment]
Hi @smjonas, not seeing the same issue any more but not seeing any highlights when using the command any more 🤔

**Comment by smjonas** [comment]
Thanks for the feedback, are you sure highlights are not working at all? Since the latest version, they should only be disabled when the entered name consists of whitespace only.

**Comment by akinsho** [comment]
@smjonas I just checked, and it seems to be using the `cword` mapping in the README no longer works e.g
```lua
    use({
      'smjonas/inc-rename.nvim',
      config = function()
        require('inc_rename').setup({ hl_group = 'Visual' })
        as.nnoremap('<leader>ri', function()
          return ':IncRename ' .. vim.fn.expand('<cword>')
        end, { expr = true, desc = 'lsp: incremental rename' })
      end,
    })
```

When I just call `IncRename` with no `cword` that works fine but using the above mapping does not work anymore

**Comment by smjonas** [comment]
Sorry for asking so many questions, but: If by "not working" you mean no highlights being shown immediately after `<leader>ri` was typed then I think this has always been the case. The reason is that the LSP request is asynchronous so the response is only processed when the first character is typed (= the second invocation of the preview callback).
If I misunderstood you (e.g. the highlights don't work after the first characters were typed), please let me know!

**Comment by akinsho** [comment]
@smjonas thanks bearing with me, just retried it and seems to be working fine now 👍🏿 gonna closet this out. Thanks for the earlier fix

**Comment by smjonas** [comment]
No worries at all, actually I also noticed the highlights sometimes do not work when typing a character so this is definitely a bug. However, it only seems to occur sometimes, weird :thinking:
